events {
    worker_connections 1024;
}

http {
    client_header_buffer_size 64k;
    large_client_header_buffers 4 64k;
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    # Forward to oqs-server-proxy (Keycloak / Bank Issuer / Resource Server)
    server {
        listen 19443;
        server_name oqs-tpp-outbound;

        location / {
            proxy_pass https://oqs-server-proxy:8443;
            
            # mTLS Client Authentication
            proxy_ssl_certificate         /certs/tpp.crt;
            proxy_ssl_certificate_key     /certs/tpp.key;
            proxy_ssl_trusted_certificate /certs/ca.crt;
            proxy_ssl_verify              on;
            proxy_ssl_protocols           TLSv1.3;
            proxy_ssl_conf_command Groups X25519MLKEM768:secp256r1:x25519;

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    # Forward to oqs-wallet-inbound (TPP -> Wallet via mTLS)
    server {
        listen 15443;
        server_name oqs-tpp-outbound;

        location / {
            proxy_pass https://oqs-wallet-inbound:5443;
            
            # mTLS Client Authentication
            proxy_ssl_certificate         /certs/tpp.crt;
            proxy_ssl_certificate_key     /certs/tpp.key;
            proxy_ssl_trusted_certificate /certs/ca.crt;
            proxy_ssl_verify              on;
            proxy_ssl_protocols           TLSv1.3;
            proxy_ssl_conf_command Groups X25519MLKEM768:secp256r1:x25519;

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
